src-git packages git@github.com:DeepRoc/openwrt-packages.git;SDK1
src-git luci https://git.openwrt.org/project/luci.git
src-git routing https://git.openwrt.org/feed/routing.git
src-git telephony https://git.openwrt.org/feed/telephony.git
src-git video git@github.com:DeepRoc/openwrt-video.git;SDK1
src-git custom git@github.com:DeepRoc/openwrt-custom.git
